import type { Metadata } from 'next';
import React, { type ReactNode } from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/global.css';
import { ThemeProvider } from '../context/ThemeContext';
import Header from '../components/Header';
import Nav from '../components/Nav';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black dark:text-white`}>
				<ThemeProvider>
					<Header />
					<Nav />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
